# InfraHooks.cmake - Hook mechanism

if(DEFINED INFRA_HOOKS_INCLUDED)
    return()
endif()
set(INFRA_HOOKS_INCLUDED TRUE)

macro(infra_hook_append HOOK_NAME)
    if(NOT DEFINED INFRA_HOOK_${HOOK_NAME})
        set(INFRA_HOOK_${HOOK_NAME} "" CACHE INTERNAL "")
    endif()
    list(APPEND INFRA_HOOK_${HOOK_NAME} ${ARGN})
endmacro()

macro(infra_hook_run HOOK_NAME)
    if(DEFINED "INFRA_HOOK_${HOOK_NAME}")
        foreach(H IN LISTS "INFRA_HOOK_${HOOK_NAME}")
            if(EXISTS "${H}")
                include("${H}")
            elseif(COMMAND "${H}")
                cmake_language(CALL "${H}")
            endif()
        endforeach()
    endif()
endmacro()

macro(infra_hook_load_dir DIR_PATH)
    if(EXISTS "${DIR_PATH}")
        file(GLOB HOOK_FILES "${DIR_PATH}/*.cmake")
        foreach(H IN LISTS HOOK_FILES)
            get_filename_component(N "${H}" NAME_WE)
            infra_hook_append("${N}" "${H}")
        endforeach()
    endif()
endmacro()

macro(infra_hook_reset)
    get_cmake_property(VARS VARIABLES)
    foreach(V IN LISTS VARS)
        if(V MATCHES "^INFRA_HOOK_")
            unset("${V}" CACHE)
        endif()
    endforeach()
endmacro()